import fs from 'node:fs';
const content = JSON.parse(fs.readFileSync(new URL('content/pt-BR.json', import.meta.url), 'utf8'));
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
import { projects, cards, dialogs, filters } from './portfolio.mjs';
import { clientSections } from './client-sections.mjs';
const roll = text => `<span class="roll"><span>${text}</span><span aria-hidden="true">${text}</span></span>`;
const team = [['samuel','Samuel Henrique'],['guilherme','Guilherme Henrique'],['adryan','Adryan Francisco'],['wendell','Wendell Nascimento']];
const html = `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#ffffff"><meta name="description" content="Sites, aplicativos e sistemas sob medida para simplificar o seu negócio."><title>404Devs — Da ideia ao sistema.</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/fonts/bricolage-grotesque-700.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="style.css?v=6"><script src="script.js?v=5" defer></script></head><body>
<a href="#principal" class="skip">Pular para conteúdo</a><div class="scroll-progress" aria-hidden="true"></div>
<header><a href="#" class="brand" aria-label="404Devs, início">404devs<span>®</span></a><nav aria-label="Principal"><a href="#projetos">${roll('Projetos')}</a><a href="#sobre">${roll('Estúdio')}</a><a href="#processo">${roll('Como trabalhamos')}</a><a href="#avaliacoes">${roll('Avaliações')}</a><a href="#duvidas">${roll('Dúvidas')}</a><a href="#contato">${roll('Vamos conversar ↗')}</a></nav><button id="motion" aria-pressed="false" aria-label="Pausar animações" title="Pausar animações">Ⅱ</button></header>
<main id="principal"><section class="hero"><div class="dot-field" aria-hidden="true"></div><h1 aria-label="Tiramos sua operação da planilha. E sua ideia do papel."><span class="line"><span>TIRAMOS SUA OPERAÇÃO</span></span><span class="line"><span>DA <em>PLANILHA.</em></span></span><span class="line"><span>E SUA IDEIA <em>DO PAPEL.</em></span></span></h1><p>Quatro desenvolvedores. Sites, aplicativos e sistemas<br class="desktop"> sob medida para simplificar o seu negócio.</p><a href="#contato" class="button magnetic">${roll('Vamos construir juntos ↗')}</a><div class="hero-bottom"><span class="label">CNPJ ATIVO · NOTA FISCAL</span><a href="#projetos" class="scroll-cue" aria-label="Ver os projetos">↓</a><span class="label">${String(projects.length).padStart(2,'0')} PROJETOS / 04 DEVS</span></div></section>
<section class="projects" id="projetos"><div class="section-heading wrap"><span class="label">01 / TRABALHOS SELECIONADOS</span><span class="label">PROJETOS PARA VER DE PERTO ↓</span></div>${filters}${cards}</section>
<section class="about dark" id="sobre"><div class="wrap"><div class="section-heading"><span class="label">02 / QUEM ESTÁ POR TRÁS</span><span class="label">QUATRO PESSOAS. UMA EQUIPE.</span></div><h2 class="reveal">GENTE DE VERDADE.<br>CÓDIGO BEM FEITO.<br><span class="outline">DO INÍCIO AO FIM.</span></h2><div class="about-copy"><span class="asterisk" aria-hidden="true">✳</span><p>Somos quatro desenvolvedores. Construímos sistemas de gestão, sites e aplicativos para empresas que precisam organizar o que hoje está no papel, no WhatsApp e no Excel.</p></div><div class="team">${team.map((t,i)=>`<figure class="reveal"><div class="portrait"><img src="assets/img/team/${t[0]}.webp" alt="${t[1]}" loading="lazy" width="600" height="600"><span>0${i+1} ↗</span></div><figcaption><strong>${t[1]}</strong><span>${esc(content.team.members[i].role)}</span></figcaption></figure>`).join('')}</div></div></section>
<section class="services wrap" id="servicos"><div class="section-heading"><span class="label">03 / O QUE FAZEMOS</span><span class="label">SEU DESAFIO. NOSSA PRÓXIMA ENTREGA.</span></div><h2 class="reveal">COMPLEXO POR DENTRO.<br><span class="muted">SIMPLES PARA VOCÊ.</span></h2><div class="service-list">${[['Sistemas sob medida','Gestão e automação para tirar sua operação da planilha e do caderno. Produção, estoque, reservas e informações no mesmo lugar.'],['Sites & aplicativos','Experiências digitais pensadas para seu negócio, com navegação clara e interfaces adaptadas a diferentes telas.'],['Integrações & dados','Coleta via API, integração entre ferramentas e exportação de dados para facilitar o trabalho da sua equipe.']].map((s,i)=>`<details><summary><span class="label">0${i+1}</span><span>${s[0]}</span><i>+</i></summary><p>${s[1]}</p></details>`).join('')}</div></section>
${clientSections(content)}
<section class="contact dark" id="contato"><div class="wrap"><div class="section-heading"><span class="label">08 / SUA IDEIA COMEÇA AQUI</span><span class="label">SÃO PAULO · BRASIL</span></div><a class="contact-title" href="https://wa.me/5517996142053" target="_blank" rel="noreferrer"><span>VAMOS TIRAR</span><span><em>DO PAPEL?</em> <i>↗</i></span></a><div class="contact-bottom"><div class="mini-team">${team.map(t=>`<img src="assets/img/team/${t[0]}.webp" alt="" width="44" height="44" loading="lazy">`).join('')}<span>Uma conversa.<br>Muitas possibilidades.</span></div><a class="button inverse magnetic" href="https://wa.me/5517996142053" target="_blank" rel="noreferrer">${roll('Falar no WhatsApp ↗')}</a></div><footer><a href="mailto:404devsoficial@gmail.com">404devsoficial@gmail.com ↗</a><a href="https://www.instagram.com/404devs.ofc/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="#">Voltar ao topo ↑</a><span>404DEVS © 2026</span></footer></div></section></main>
${dialogs}
</body></html>`;
fs.writeFileSync(new URL('index.html', import.meta.url),html);
console.log(`Protótipo gerado com ${projects.length} projetos e ${projects.reduce((total,p)=>total+p.images.length,0)} imagens.`);
